name: Build Application

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Pull code
          uses: actions/checkout@v2

        - name: Print current directory
          run: pwd

        - name: List Files
          run: ls -a

        - name: Build solution
          run: dotnet build

        - name: Show solution items
          run: ls .\TrickingLibrary.Api -R

        - name: Check npm
          run: npm -v